name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Q1
      id: q1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Q1
        setup-command: ''
        command: pytest test_stats_lab.py::test_q1_normal
        timeout: 10
        max-score: 10
    - name: Q1
      id: q1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Q1
        setup-command: ''
        command: pytest test_stats_lab.py::test_q1_uniform
        timeout: 10
        max-score: 10
    - name: Q1
      id: q1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Q1
        setup-command: ''
        command: pytest test_stats_lab.py::test_q1_bernoulli
        timeout: 10
        max-score: 10
    - name: Q2
      id: q2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Q2
        setup-command: ''
        command: pytest test_stats_lab.py::test_q2_variance
        timeout: 10
        max-score: 10
    - name: Q3
      id: q3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Q3
        setup-command: ''
        command: pytest test_stats_lab.py::test_q3_order_statistics
        timeout: 10
        max-score: 20
    - name: Q4
      id: q4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Q4
        setup-command: ''
        command: pytest test_stats_lab.py::test_q5_covariance_matrix
        timeout: 10
        max-score: 15
    - name: Q5
      id: q5
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Q5
        setup-command: ''
        command: pytest test_stats_lab.py::test_q5_covariance_matrix
        timeout: 10
        max-score: 15
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        Q1_RESULTS: "${{steps.q1.outputs.result}}"
        Q2_RESULTS: "${{steps.q2.outputs.result}}"
        Q3_RESULTS: "${{steps.q3.outputs.result}}"
        Q4_RESULTS: "${{steps.q4.outputs.result}}"
        Q5_RESULTS: "${{steps.q5.outputs.result}}"
      with:
        runners: q1,q1,q1,q2,q3,q4,q5
